CREATE DATABASE IF NOT EXISTS novanest_db;
USE novanest_db;

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    price INT NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    image_url VARCHAR(255) NOT NULL,
    badge VARCHAR(50) DEFAULT 'Featured',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    total_amount INT NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
INSERT INTO categories (name, slug) VALUES
('Electronics','electronics'),
('Fashion','fashion'),
('Home Decor','home-decor'),
('Beauty','beauty'),
('Sports','sports');

INSERT INTO products (category_id, name, description, price, stock, image_url, badge) VALUES
(1,'Nova Wireless Earbuds','Nova Wireless Earbuds is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',9033,10,'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80','Featured'),
(1,'Titan Smartwatch','Titan Smartwatch is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7003,84,'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80','New Arrival'),
(1,'Aero Bluetooth Speaker','Aero Bluetooth Speaker is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',13270,18,'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=800&q=80','Limited'),
(1,'Fusion Power Bank','Fusion Power Bank is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',4299,14,'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80','New Arrival'),
(1,'Clarity 4K Webcam','Clarity 4K Webcam is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7100,59,'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80','Featured'),
(1,'Zen Noise Cancelling Headphones','Zen Noise Cancelling Headphones is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',8863,74,'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80','Limited'),
(1,'Flash Portable SSD','Flash Portable SSD is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',3298,77,'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80','Best Seller'),
(1,'Halo Ring Light','Halo Ring Light is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7085,78,'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80','Best Seller'),
(1,'Turbo Fast Charger','Turbo Fast Charger is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',10927,30,'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80','New Arrival'),
(1,'Phantom Gaming Mouse','Phantom Gaming Mouse is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',18001,75,'https://images.unsplash.com/photo-1563297007-0686b7003af7?auto=format&fit=crop&w=800&q=80','Featured'),
(2,'Signature Linen Shirt','Signature Linen Shirt is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',4820,46,'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80','Best Seller'),
(2,'Elite Tailored Blazer','Elite Tailored Blazer is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',3009,25,'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80','New Arrival'),
(2,'Velvet Grace Dress','Velvet Grace Dress is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',6675,37,'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80','New Arrival'),
(2,'Classic Leather Belt','Classic Leather Belt is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',5023,68,'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=800&q=80','New Arrival'),
(2,'Urban Luxe Sneakers','Urban Luxe Sneakers is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',4706,77,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80','Best Seller'),
(2,'Pure Cashmere Scarf','Pure Cashmere Scarf is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7454,21,'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=800&q=80','Limited'),
(2,'Iconic Tote Bag','Iconic Tote Bag is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',8264,85,'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80','Best Seller'),
(2,'Slim Comfort Chinos','Slim Comfort Chinos is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',9383,10,'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80','Featured'),
(2,'Premium Denim Jacket','Premium Denim Jacket is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2100,40,'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80','Featured'),
(2,'Silk Blend Kurta','Silk Blend Kurta is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',3399,37,'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&w=800&q=80','Best Seller'),
(3,'Nordic Ceramic Vase','Nordic Ceramic Vase is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',1517,39,'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=800&q=80','Featured'),
(3,'Aura Table Lamp','Aura Table Lamp is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2171,76,'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80','Featured'),
(3,'Handwoven Throw Blanket','Handwoven Throw Blanket is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',982,33,'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80','Featured'),
(3,'Minimal Wall Clock','Minimal Wall Clock is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2156,38,'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80','Limited'),
(3,'Marble Accent Tray','Marble Accent Tray is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7009,89,'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80','New Arrival'),
(3,'Oak Candle Holder','Oak Candle Holder is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',4526,15,'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80','Featured'),
(3,'Modern Planter Set','Modern Planter Set is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',1425,43,'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80','Best Seller'),
(3,'Textured Cushion Cover','Textured Cushion Cover is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7824,67,'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80','Best Seller'),
(3,'Framed Vanity Mirror','Framed Vanity Mirror is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',3356,26,'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=800&q=80','Best Seller'),
(3,'Artisan Floor Rug','Artisan Floor Rug is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',1885,77,'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80','Limited'),
(4,'Radiance Face Serum','Radiance Face Serum is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2207,89,'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80','Featured'),
(4,'Velvet Matte Lip Kit','Velvet Matte Lip Kit is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',1123,24,'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80','New Arrival'),
(4,'Hydra Glow Moisturizer','Hydra Glow Moisturizer is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',885,26,'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=800&q=80','Best Seller'),
(4,'Botanical Hair Elixir','Botanical Hair Elixir is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2359,69,'https://images.unsplash.com/photo-1619451334792-150fd785ee74?auto=format&fit=crop&w=800&q=80','Best Seller'),
(4,'Silk Touch Foundation','Silk Touch Foundation is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',1357,51,'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80','Best Seller'),
(4,'Rose Clay Mask','Rose Clay Mask is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',1254,27,'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80','Limited'),
(4,'Luminous Highlighter Palette','Luminous Highlighter Palette is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',3279,14,'https://images.unsplash.com/photo-1631730486572-226b7760e72f?auto=format&fit=crop&w=800&q=80','Limited'),
(4,'Herbal Body Mist','Herbal Body Mist is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2647,56,'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=800&q=80','Featured'),
(4,'Overnight Repair Cream','Overnight Repair Cream is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2043,49,'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?auto=format&fit=crop&w=800&q=80','Featured'),
(4,'Precision Brush Set','Precision Brush Set is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',2378,36,'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80','Best Seller'),
(5,'Performance Yoga Mat','Performance Yoga Mat is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',12543,78,'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80','New Arrival'),
(5,'Endurance Water Bottle','Endurance Water Bottle is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',8265,52,'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80','Limited'),
(5,'Pro Resistance Bands','Pro Resistance Bands is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',889,83,'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80','Limited'),
(5,'Aero Running Shoes','Aero Running Shoes is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',12226,49,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80','New Arrival'),
(5,'Core Fitness Roller','Core Fitness Roller is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',12392,58,'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80','Best Seller'),
(5,'Grip Training Gloves','Grip Training Gloves is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',4385,54,'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=80','Best Seller'),
(5,'Speed Jump Rope','Speed Jump Rope is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',7165,27,'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=800&q=80','Best Seller'),
(5,'Trail Duffel Bag','Trail Duffel Bag is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',11708,40,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80','Featured'),
(5,'Flex Dry-Fit T-Shirt','Flex Dry-Fit T-Shirt is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',10393,52,'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80','Best Seller'),
(5,'Power Kettlebell','Power Kettlebell is designed for customers who want premium quality, clean aesthetics, and dependable performance. It delivers stylish presentation, lasting comfort, and great everyday value for modern lifestyles.',10554,16,'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&w=800&q=80','Limited');
